name: Build
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '1 1 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # checkout all branches
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Generate blocklists and badges
      run: |
        sudo python3 generate-domains-blocklist.py -o blocklist.txt
        sudo cp -rf *.txt /tmp
    - name: Remove remote data branch
      if: ${{ success() }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git push origin :data
    - name: Checkout
      if: ${{ success() }}
      run: |
        git checkout --orphan data
        git rm -rf .
        cp -rf /tmp/*.txt .
    - name: Add files
      if: ${{ success() }}
      run: |
        git add .
    - name: Commit Push
      if: ${{ success() }}
      run: |
        git commit -m "blocklist generated"
        git push origin data
        
