name: build
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          sudo python generate-domains-blocklist.py > blocklist.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push
