name: build
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        run: sudo python generate-domains-blocklist.py -o blocklist.txt

      - uses: actions/checkout@v1
      - name: Commit report
        run: |
          git config --global user.name 't0ny54'
          git config --global user.email 't0ny54@users.noreply.github.com'
          git remote set-url origin/main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated report"
          git push

      - name: Upload generated Blocklist file
        uses: actions/upload-artifact@v2
        with:
          name: blocklist
          path: blocklist.txt
          
