name: build
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '30 1 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        run: sudo python generate-domains-blocklist.py -o blocklist.txt
        sudo cp -rf *.txt /tmp
        git config user.name github-actions
        git config user.email github-actions@github.com
        git push origin :data
        git checkout --orphan data
        cp -rf /tmp/*.txt
        git commit -m "blocklist generated"
        git push origin data

      - name: Upload generated Blocklist file
        uses: actions/upload-artifact@v2
        with:
          name: blocklist
          path: blocklist.txt
          
