name: build
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        run: sudo python generate-domains-blocklist.py -o blocklist.txt
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions

      - name: Upload generated Blocklist file
        uses: actions/upload-artifact@v2
        with:
          name: blocklist
          path: blocklist.txt
          
